In [1]:
import numpy as np
ret_arr = np.array([[4, 2], [5, 4], [2, 6], [10, 21], [4,0]])
payloads = np.array(['asdsd', 'bwww', 'coo', 'ezz'])
index = np.argsort(ret_arr[:,0], axis=0)

In [2]:
ret_arr = ret_arr[index]

In [3]:
np.savetxt("test.csv", ret_arr, delimiter=",", fmt='%d')
#np.savetxt("test.csv", payloads, delimiter=",", fmt='%s')

In [4]:
ret_arr[:,0]

array([ 2,  4,  4,  5, 10])

In [5]:
index

array([2, 0, 4, 1, 3])

In [6]:
ret_arr

array([[ 2,  6],
       [ 4,  2],
       [ 4,  0],
       [ 5,  4],
       [10, 21]])