In [1]:
import os
import shutil
import itertools
import time
import csv
import numpy as np
meta = dict()
process_num = 8
docu = 'real_data_6219'
threshold = 4

In [2]:
from Parallel import *

In [3]:
a = np.array([[0, 1], [5, 3], [9, 5], [7, 8]])
idx = np.argmin(a, axis=1)

if threshold != 99999:
    dist = np.min(a, axis=1)
    filtered_idx = dist > 4
    idx[filtered_idx] = -1

In [4]:
a

array([[0, 1],
       [5, 3],
       [9, 5],
       [7, 8]])

In [10]:
len(idx)

4

In [6]:
dist

array([0, 3, 5, 7])

In [7]:
filtered_idx

array([False, False,  True,  True])

In [8]:
idx[filtered_idx] = -1

In [9]:
idx 

array([ 0,  1, -1, -1])